/**
 * Type-gen smoke check.
 *
 * Verifies the generated `api-types.generated.ts` file exists, parses as
 * valid TypeScript, and exposes the path + schema names the frontend imports.
 */
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

import type {
  AgentSpec,
  EdgeSpec,
  ExecutionConfigSpec,
  ModelConfigSpec,
  NodeSpec,
  TopologySpec,
  Workflow,
  WorkflowCreateRequest,
  WorkflowDefinition,
  WorkflowListResponse,
  paths,
} from "../src/lib/api";

const GENERATED = resolve(__dirname, "../src/lib/api-types.generated.ts");

describe("type generation", () => {
  it("generated file exists and is non-empty", () => {
    expect(existsSync(GENERATED)).toBe(true);
    const source = readFileSync(GENERATED, "utf8");
    expect(source.length).toBeGreaterThan(1000);
  });

  it("emitted by openapi-typescript", () => {
    const source = readFileSync(GENERATED, "utf8");
    expect(source).toContain("auto-generated by openapi-typescript");
  });

  it("declares the workflow paths", () => {
    const source = readFileSync(GENERATED, "utf8");
    expect(source).toContain('"/v1/workflows"');
    expect(source).toContain('"/v1/workflows/{workflow_id}"');
    expect(source).toContain('"/v1/workflows/import-python"');
  });

  it("Workflow type round-trips with a JSON sample", () => {
    const sample: Workflow = {
      id: "01HXXX",
      name: "demo",
      description: null,
      definition: {
        topology: { nodes: [], edges: [], rules: [] },
        agents: {},
        execution_config: {},
      },
      definition_version: 1,
      provenance: "api",
      provenance_metadata: null,
      is_archived: false,
      created_at: "2026-05-10T00:00:00Z",
      updated_at: "2026-05-10T00:00:00Z",
    };
    expect(sample.provenance).toBe("api");
    expect(sample.definition.agents).toEqual({});
  });

  it("paths type narrows GET /v1/workflows response", () => {
    type ListGet = paths["/v1/workflows"]["get"];
    type Response200 = ListGet["responses"][200];
    const literal: Response200["content"]["application/json"] = {
      items: [],
      next_cursor: null,
      has_more: false,
    } as unknown as Response200["content"]["application/json"];
    expect(literal).toBeDefined();
  });

  it("WorkflowCreateRequest accepts a minimal payload", () => {
    const req: WorkflowCreateRequest = {
      name: "minimal",
      definition: {
        topology: { nodes: [], edges: [], rules: [] },
        agents: {},
        execution_config: {},
      },
    };
    expect(req.name).toBe("minimal");
  });

  it("WorkflowListResponse has the cursor-pagination shape", () => {
    const empty: WorkflowListResponse = {
      items: [],
      next_cursor: null,
      has_more: false,
    };
    expect(empty.has_more).toBe(false);
  });

  it("ModelConfigSpec accepts mixed provider per agent", () => {
    const openai: ModelConfigSpec = { type: "api", name: "gpt-4o", provider: "openai" };
    const anthropic: ModelConfigSpec = { type: "api", name: "claude-opus-4-7", provider: "anthropic" };
    expect(openai.provider).toBe("openai");
    expect(anthropic.provider).toBe("anthropic");
  });

  it("ModelConfigSpec does NOT carry api_key", () => {
    const source = readFileSync(GENERATED, "utf8");
    const start = source.indexOf("ModelConfigSpec: {");
    const end = source.indexOf("};", start);
    const body = source.slice(start, end);
    expect(body).not.toContain("api_key");
  });

  it("AgentSpec has agent_model not model_config", () => {
    const sample: AgentSpec = {
      agent_model: { type: "api", name: "gpt-4o", provider: "openai" },
      name: "X",
      goal: "g",
      instruction: "i",
    };
    expect(sample.agent_model.name).toBe("gpt-4o");
  });

  it("topology / node / edge / execution-config types exist", () => {
    const node: NodeSpec = { name: "X", node_type: "agent" };
    const edge: EdgeSpec = { source: "A", target: "B" };
    const topo: TopologySpec = { nodes: [node], edges: [edge] };
    const exec: ExecutionConfigSpec = {};
    const defn: WorkflowDefinition = { topology: topo, agents: {}, execution_config: exec };
    expect(defn.topology?.nodes?.[0]?.name).toBe("X");
  });
});
