/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bootstrap */
        get: operations["bootstrap_v1_bootstrap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workflows */
        get: operations["list_workflows_v1_workflows_get"];
        put?: never;
        /** Create Workflow */
        post: operations["create_workflow_v1_workflows_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workflows/{workflow_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Workflow */
        get: operations["read_workflow_v1_workflows__workflow_id__get"];
        /** Replace Workflow */
        put: operations["replace_workflow_v1_workflows__workflow_id__put"];
        post?: never;
        /** Delete Workflow */
        delete: operations["delete_workflow_v1_workflows__workflow_id__delete"];
        options?: never;
        head?: never;
        /** Patch Workflow */
        patch: operations["patch_workflow_v1_workflows__workflow_id__patch"];
        trace?: never;
    };
    "/v1/workflows/import-python": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Python Workflow */
        post: operations["import_python_workflow_v1_workflows_import_python_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tools */
        get: operations["list_tools_v1_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workflows/{workflow_id}/lint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lint Endpoint */
        post: operations["lint_endpoint_v1_workflows__workflow_id__lint_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentSpec */
        AgentSpec: {
            agent_model: components["schemas"]["ModelConfigSpec"];
            /** Name */
            name: string;
            /** Goal */
            goal: string;
            /** Instruction */
            instruction: string;
            /** Tools */
            tools?: string[];
            /**
             * Memory Retention
             * @default session
             * @enum {string}
             */
            memory_retention?: "single_run" | "session" | "persistent";
            /** Allowed Peers */
            allowed_peers?: string[];
        };
        /** Body_import_python_workflow_v1_workflows_import_python_post */
        Body_import_python_workflow_v1_workflows_import_python_post: {
            /** File */
            file: string;
        };
        /** BootstrapResponse */
        BootstrapResponse: {
            framework: components["schemas"]["FrameworkInfo"];
            spren: components["schemas"]["SprenInfo"];
            /** Surfaces */
            surfaces: string[];
            /** Capabilities */
            capabilities: {
                [key: string]: boolean;
            };
            /** Endpoints */
            endpoints: {
                [key: string]: string;
            };
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Data Dir */
            data_dir: string;
        };
        /** ConvergencePolicyConfigSpec */
        ConvergencePolicyConfigSpec: {
            /**
             * Min Ratio
             * @default 1
             */
            min_ratio?: number;
            /**
             * On Insufficient
             * @default fail
             * @enum {string}
             */
            on_insufficient?: "proceed" | "fail" | "user";
            /**
             * Terminate Orphans
             * @default true
             */
            terminate_orphans?: boolean;
            /**
             * Log Level
             * @default warning
             * @enum {string}
             */
            log_level?: "info" | "warning" | "error";
        };
        /**
         * EdgePattern
         * @enum {string}
         */
        EdgePattern: "alternating" | "symmetric";
        /** EdgeSpec */
        EdgeSpec: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** @default invoke */
            edge_type?: components["schemas"]["EdgeType"];
            /**
             * Bidirectional
             * @default false
             */
            bidirectional?: boolean;
            pattern?: components["schemas"]["EdgePattern"] | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /**
         * EdgeType
         * @enum {string}
         */
        EdgeType: "invoke" | "notify" | "query" | "stream";
        /** ErrorEnvelope */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorPayload"];
        };
        /** ErrorPayload */
        ErrorPayload: {
            /**
             * Code
             * @enum {string}
             */
            code: "WORKFLOW_NOT_FOUND" | "WORKFLOW_HAS_RUNS" | "PYTHON_IMPORT_REJECTED" | "MIGRATION_FAILED" | "VALIDATION_FAILED" | "INVALID_CURSOR" | "INTERNAL_ERROR";
            /** Message */
            message: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
        };
        /** ExecutionConfigSpec */
        ExecutionConfigSpec: {
            /**
             * Steering Mode
             * @default error
             * @enum {string}
             */
            steering_mode?: "auto" | "always" | "error";
            /**
             * Dynamic Convergence Enabled
             * @default true
             */
            dynamic_convergence_enabled?: boolean;
            /**
             * Parent Completes On Spawn
             * @default true
             */
            parent_completes_on_spawn?: boolean;
            /**
             * Auto Detect Convergence
             * @default true
             */
            auto_detect_convergence?: boolean;
            /**
             * Convergence Timeout
             * @default 300
             */
            convergence_timeout?: number;
            /**
             * Convergence Policy
             * @default 1
             */
            convergence_policy?: number | string | components["schemas"]["ConvergencePolicyConfigSpec"];
            /**
             * Branch Timeout
             * @default 600
             */
            branch_timeout?: number;
            /**
             * Agent Acquisition Timeout
             * @default 240
             */
            agent_acquisition_timeout?: number;
            /**
             * Step Timeout
             * @default 600
             */
            step_timeout?: number;
            /**
             * Tool Execution Timeout
             * @default 120
             */
            tool_execution_timeout?: number;
            /**
             * User Interaction Timeout
             * @default 300
             */
            user_interaction_timeout?: number;
            status?: components["schemas"]["StatusConfigSpec"];
            /**
             * User First
             * @default false
             */
            user_first?: boolean;
            /** Initial User Msg */
            initial_user_msg?: string | null;
            /**
             * User Interaction
             * @default none
             * @enum {string}
             */
            user_interaction?: "terminal" | "web" | "none";
            /**
             * Auto Cleanup Agents
             * @default true
             */
            auto_cleanup_agents?: boolean;
            /**
             * Cleanup Scope
             * @default topology_nodes
             * @enum {string}
             */
            cleanup_scope?: "topology_nodes" | "used_agents";
            /**
             * Response Format
             * @default json
             */
            response_format?: string;
            /**
             * Content Only Steering Threshold
             * @default 2
             */
            content_only_steering_threshold?: number;
            /**
             * Content Only Hard Limit
             * @default 10
             */
            content_only_hard_limit?: number;
        };
        /** FrameworkInfo */
        FrameworkInfo: {
            /** Version */
            version: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImportWarningPayload
         * @description A single non-blocking warning surfaced from the Python importer.
         *
         *     Currently only emitted when an alternating (``<~>``) or symmetric
         *     (``<|>``) edge pattern is auto-converted to plain bidirectional —
         *     the canvas in v0.3 only exposes uni/bi directions (Q2 lock).
         */
        ImportWarningPayload: {
            /**
             * Code
             * @constant
             */
            code: "pattern_auto_converted";
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Original Pattern */
            original_pattern: string;
            /** Message */
            message: string;
        };
        /** LintFinding */
        LintFinding: {
            /**
             * Severity
             * @enum {string}
             */
            severity: "error" | "warning";
            /**
             * Code
             * @enum {string}
             */
            code: "unreachable" | "cycle_no_escape" | "missing_agent_ref" | "unknown_tool" | "dangling_edge" | "missing_required_field";
            /** Node Name */
            node_name?: string | null;
            /** Edge */
            edge?: [
                string,
                string
            ] | null;
            /** Message */
            message: string;
            /** Suggestion */
            suggestion?: string | null;
        };
        /** LintResponse */
        LintResponse: {
            /** Findings */
            findings: components["schemas"]["LintFinding"][];
        };
        /**
         * ModelConfigSpec
         * @description Storage-boundary mirror of marsys's ModelConfig (no api_key).
         */
        ModelConfigSpec: {
            /**
             * Type
             * @enum {string}
             */
            type: "local" | "api";
            /** Name */
            name: string;
            /** Provider */
            provider?: ("openai" | "openrouter" | "google" | "anthropic" | "xai" | "openai-oauth" | "anthropic-oauth") | null;
            /** Base Url */
            base_url?: string | null;
            /**
             * Max Tokens
             * @default 8192
             */
            max_tokens?: number;
            /**
             * Temperature
             * @default 0.7
             */
            temperature?: number;
            /**
             * Thinking Budget
             * @default 1024
             */
            thinking_budget?: number | null;
            /**
             * Reasoning Effort
             * @default low
             */
            reasoning_effort?: ("minimal" | "low" | "medium" | "high") | null;
            /** Oauth Profile */
            oauth_profile?: string | null;
            /** Model Class */
            model_class?: ("llm" | "vlm") | null;
            /**
             * Backend
             * @default huggingface
             */
            backend?: ("huggingface" | "vllm") | null;
            /**
             * Torch Dtype
             * @default auto
             */
            torch_dtype?: string | null;
            /**
             * Device Map
             * @default auto
             */
            device_map?: string | null;
            /** Quantization Config */
            quantization_config?: {
                [key: string]: unknown;
            } | null;
            /**
             * Tensor Parallel Size
             * @default 1
             */
            tensor_parallel_size?: number | null;
            /**
             * Gpu Memory Utilization
             * @default 0.9
             */
            gpu_memory_utilization?: number | null;
            /** Quantization */
            quantization?: ("awq" | "gptq" | "fp8") | null;
        };
        /** NodeSpec */
        NodeSpec: {
            /** Name */
            name: string;
            /** @default agent */
            node_type?: components["schemas"]["NodeType"];
            /** Agent Ref */
            agent_ref?: string | null;
            /**
             * Is Convergence Point
             * @default false
             */
            is_convergence_point?: boolean;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /**
         * NodeType
         * @enum {string}
         */
        NodeType: "user" | "agent" | "system" | "tool";
        /** SprenInfo */
        SprenInfo: {
            /** Active */
            active: boolean;
            /** Version */
            version: string;
        };
        /** StatusConfigSpec */
        StatusConfigSpec: {
            /**
             * Enabled
             * @default false
             */
            enabled?: boolean;
            /** Verbosity */
            verbosity?: number | null;
        };
        /** ToolInfo */
        ToolInfo: {
            /** Name */
            name: string;
            /**
             * Source
             * @constant
             */
            source: "framework";
            /** Description */
            description?: string | null;
        };
        /** ToolListResponse */
        ToolListResponse: {
            /** Items */
            items: components["schemas"]["ToolInfo"][];
        };
        /** TopologySpec */
        TopologySpec: {
            /** Nodes */
            nodes?: components["schemas"]["NodeSpec"][];
            /** Edges */
            edges?: components["schemas"]["EdgeSpec"][];
            /** Rules */
            rules?: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Workflow */
        Workflow: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            definition: components["schemas"]["WorkflowDefinition"];
            /**
             * Definition Version
             * @default 1
             */
            definition_version?: number;
            /**
             * Provenance
             * @enum {string}
             */
            provenance: "visual_builder" | "meta_agent" | "code_import" | "template" | "api";
            /** Provenance Metadata */
            provenance_metadata?: {
                [key: string]: unknown;
            } | null;
            /**
             * Is Archived
             * @default false
             */
            is_archived?: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** WorkflowCreateRequest */
        WorkflowCreateRequest: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            definition: components["schemas"]["WorkflowDefinition"];
            /**
             * Provenance
             * @default api
             * @enum {string}
             */
            provenance?: "visual_builder" | "meta_agent" | "code_import" | "template" | "api";
            /** Provenance Metadata */
            provenance_metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /** WorkflowDefinition */
        WorkflowDefinition: {
            topology: components["schemas"]["TopologySpec"];
            /** Agents */
            agents?: {
                [key: string]: components["schemas"]["AgentSpec"];
            };
            execution_config?: components["schemas"]["ExecutionConfigSpec"];
        };
        /**
         * WorkflowImportResponse
         * @description The payload returned by ``POST /v1/workflows/import-python``.
         *
         *     The full ``Workflow`` is included alongside an optional ``warnings``
         *     array so the client can choose to show a toast and / or highlight
         *     the affected canvas edges.
         */
        WorkflowImportResponse: {
            workflow: components["schemas"]["Workflow"];
            /**
             * Warnings
             * @default []
             */
            warnings?: components["schemas"]["ImportWarningPayload"][];
        };
        /** WorkflowListResponse */
        WorkflowListResponse: {
            /** Items */
            items: components["schemas"]["Workflow"][];
            /** Next Cursor */
            next_cursor: string | null;
            /** Has More */
            has_more: boolean;
        };
        /**
         * WorkflowUpdateRequest
         * @description PATCH payload — every field optional, only provided fields update.
         */
        WorkflowUpdateRequest: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            definition?: components["schemas"]["WorkflowDefinition"] | null;
            /** Is Archived */
            is_archived?: boolean | null;
            /** Provenance Metadata */
            provenance_metadata?: {
                [key: string]: unknown;
            } | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    bootstrap_v1_bootstrap_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workflows_v1_workflows_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
                provenance?: ("visual_builder" | "meta_agent" | "code_import" | "template" | "api") | null;
                archived?: boolean | null;
                include_drafts?: boolean;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowListResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_workflow_v1_workflows_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workflow"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    read_workflow_v1_workflows__workflow_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workflow"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_workflow_v1_workflows__workflow_id__put: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workflow"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    delete_workflow_v1_workflows__workflow_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_workflow_v1_workflows__workflow_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workflow"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    import_python_workflow_v1_workflows_import_python_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_python_workflow_v1_workflows_import_python_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowImportResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_tools_v1_tools_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lint_endpoint_v1_workflows__workflow_id__lint_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LintResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
